### ISSUE TITLE
Change so records include requester name and organization name

### ISSUE THREAD

**Issue by wcpines** [aptible/minitron#18]
Mixpanel does not have org/company info, nor requester names. 

Currently `ticket.requester` returns an object, as does `ticket.requester.organization`. This is a bug. 

Change to/include `ticket.requester.name` and `ticket.requester.organization.name`

**Comment by wcpines** [comment]
@fancyremarker  Not sure if I can re-run backload with new info w/o duplicating everything :/

**Comment by fancyremarker** [comment]
See my comments on #19. Can you clarify what the bug is in the current implementation?

**Comment by wcpines** [comment]
Currently we can't associate tickets with orgs/users.  That's important.  Not positive how best to accomplish that.
